### ISSUE TITLE
Could not compile on Ubuntu 21.10

### ISSUE THREAD

**Issue by leoxshn** [Doomsdayrs/gtk-kt#12]
I installed the necessary packages from the README with `sudo apt install libgtk-4-dev libncurses5`, but it seems that there's still something missing.
When run `./gradlew publishToMavenLocal`, this happens:
```
> Task :src:gtk:cinteropGtkNative FAILED
Exception in thread "main" java.lang.Error: /usr/include/limits.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
        at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:192)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:1206)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:1195)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:1191)
        at org.jetbrains.kotlin.native.interop.gen.jvm.DefaultPlugin.buildNativeIndex(Plugins.kt:31)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:272)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:76)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)
        at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:38)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:60)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':src:gtk:cinteropGtkNative'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
25 actionable tasks: 4 executed, 21 up-to-date
```

**Comment by sobotkami** [comment]
Hi, I don't use Ubuntu, however this header file could be located in gcc-multilib:

`sudo apt-get install gcc-multilib`

**Comment by Doomsdayrs** [comment]
Added as a dependency in 78ebc84

@leoxshn Can you install the library and try again?

**Comment by leoxshn** [comment]
That fixed it
